import {SERVICES,validateGraph,terraform,cdk} from './generator.js';
const $=s=>document.querySelector(s), canvas=$('#canvas'), edgesSvg=$('#edges');let graph={nodes:[],edges:[]},selected=null,mode='select',connectFrom=null,format='terraform';
function renderPalette(filter=''){const p=$('#palette');p.innerHTML='';for(const [type,s] of Object.entries(SERVICES).filter(([,s])=>`${s.label} ${s.category}`.toLowerCase().includes(filter.toLowerCase()))){const e=document.createElement('div');e.className='service';e.draggable=true;e.innerHTML=`<span class="icon" style="background:${s.color}">${s.label[0]}</span><span>${s.label}<small style="display:block;color:#7f8da3">${s.category}</small></span>`;e.ondragstart=x=>x.dataTransfer.setData('type',type);p.append(e)}}
canvas.ondragover=e=>e.preventDefault();canvas.ondrop=e=>{e.preventDefault();const type=e.dataTransfer.getData('type');if(!SERVICES[type])return;const r=canvas.getBoundingClientRect(),count=graph.nodes.filter(n=>n.type===type).length+1;graph.nodes.push({id:crypto.randomUUID(),type,name:type==='s3'?`cloudsketch-${Date.now()}`:`${SERVICES[type].label} ${count}`,x:e.clientX-r.left-70,y:e.clientY-r.top-35,props:{...SERVICES[type].defaults}});render()};
function render(){canvas.querySelectorAll('.node').forEach(n=>n.remove());$('#empty').style.display=graph.nodes.length?'none':'grid';for(const n of graph.nodes){const e=document.createElement('div');e.className='node'+(selected?.kind==='node'&&selected.id===n.id?' selected':'');e.style.cssText+=`left:${n.x}px;top:${n.y}px;border-top:4px solid ${SERVICES[n.type].color}`;e.innerHTML=`<div class="title">${n.name}</div><div class="type">${SERVICES[n.type].label}</div><i class="dot in"></i><i class="dot out"></i>`;let drag;e.onpointerdown=x=>{if(mode==='connect'){if(!connectFrom){connectFrom=n.id;$('#status').textContent='Select target resource'}else if(connectFrom!==n.id){graph.edges.push({id:crypto.randomUUID(),source:connectFrom,target:n.id});connectFrom=null;$('#status').textContent='Connection created';render()}return}selected={kind:'node',id:n.id};drag={dx:x.clientX-n.x,dy:x.clientY-n.y};e.setPointerCapture(x.pointerId);renderProperties();render()};e.onpointermove=x=>{if(!drag||mode!=='select')return;const r=canvas.getBoundingClientRect();n.x=Math.max(0,x.clientX-r.left-drag.dx);n.y=Math.max(0,x.clientY-r.top-drag.dy);drawEdges()};e.onpointerup=()=>drag=null;canvas.append(e)}drawEdges()}
function drawEdges(){edgesSvg.innerHTML='';for(const ed of graph.edges){const a=graph.nodes.find(n=>n.id===ed.source),b=graph.nodes.find(n=>n.id===ed.target);if(!a||!b)continue;const p=document.createElementNS('http://www.w3.org/2000/svg','path');const x1=a.x+142,y1=a.y+34,x2=b.x,y2=b.y+34,m=(x1+x2)/2;p.setAttribute('d',`M${x1},${y1} C${m},${y1} ${m},${y2} ${x2},${y2}`);p.setAttribute('class','edge');edgesSvg.append(p)}}
function renderProperties(){const n=selected?.kind==='node'&&graph.nodes.find(x=>x.id===selected.id),box=$('#properties');if(!n){box.innerHTML='<p>Select a resource.</p>';return}box.innerHTML='';const fields={name:n.name,...n.props};for(const [k,v] of Object.entries(fields)){const d=document.createElement('div');d.className='field';d.innerHTML=`<label>${k}</label><input value="${String(v).replaceAll('"','&quot;')}">`;d.querySelector('input').oninput=e=>{if(k==='name')n.name=e.target.value;else n.props[k]=e.target.value;render()};box.append(d)}}
function validate(){const issues=validateGraph(graph),box=$('#issues');box.innerHTML=issues.length?issues.map(i=>`<div class="issue ${i.level}">${i.message}</div>`).join(''):'<p>✓ No issues found.</p>';$('#status').textContent=`${issues.length} issue${issues.length===1?'':'s'}`}
function setMode(m){mode=m;connectFrom=null;$('#selectMode').classList.toggle('active',m==='select');$('#connectMode').classList.toggle('active',m==='connect');$('#status').textContent=m==='connect'?'Select source resource':'Select and move resources'}
$('#search').oninput=e=>renderPalette(e.target.value);$('#selectMode').onclick=()=>setMode('select');$('#connectMode').onclick=()=>setMode('connect');$('#validate').onclick=validate;$('#deleteSelection').onclick=()=>{if(selected?.kind==='node'){graph.nodes=graph.nodes.filter(n=>n.id!==selected.id);graph.edges=graph.edges.filter(e=>e.source!==selected.id&&e.target!==selected.id);selected=null;renderProperties();render()}};
$('#saveJson').onclick=()=>download('cloudsketch-architecture.json',JSON.stringify(graph,null,2));$('#loadJson').onchange=async e=>{graph=JSON.parse(await e.target.files[0].text());selected=null;renderProperties();render()};$('#loadExample').onclick=()=>{graph={nodes:[{id:'v',type:'vpc',name:'App VPC',x:40,y:130,props:{cidr:'10.0.0.0/16'}},{id:'s',type:'subnet',name:'Public Subnet',x:250,y:130,props:{cidr:'10.0.1.0/24',public:'true'}},{id:'a',type:'apigw',name:'Public API',x:460,y:40,props:{}},{id:'l',type:'lambda',name:'Order Handler',x:660,y:40,props:{runtime:'nodejs20.x',handler:'index.handler'}},{id:'d',type:'dynamodb',name:'Orders',x:660,y:180,props:{partitionKey:'id'}},{id:'b',type:'s3',name:`cloudsketch-assets-${Date.now()}`,x:460,y:250,props:{versioning:'true'}}],edges:[{id:'1',source:'v',target:'s'},{id:'2',source:'a',target:'l'},{id:'3',source:'l',target:'d'},{id:'4',source:'l',target:'b'}]};render()};
function generated(){return format==='terraform'?terraform(graph):cdk(graph)}function showCode(){validate();$('#code').textContent=generated();$('#codeDialog').showModal()}$('#exportCode').onclick=showCode;document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{format=b.dataset.format;document.querySelectorAll('[data-format]').forEach(x=>x.classList.toggle('active',x===b));$('#code').textContent=generated()});$('#copyCode').onclick=()=>navigator.clipboard.writeText(generated());$('#downloadCode').onclick=()=>download(format==='terraform'?'main.tf':'cloudsketch-stack.ts',generated());function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}renderPalette();render();
