export const SERVICES = {
  vpc:{label:'VPC',color:'#8c4fff',category:'Network',defaults:{cidr:'10.0.0.0/16'}},
  subnet:{label:'Subnet',color:'#8c4fff',category:'Network',defaults:{cidr:'10.0.1.0/24',public:'true'}},
  security_group:{label:'Security Group',color:'#dd344c',category:'Security',defaults:{description:'Managed by CloudSketch'}},
  ec2:{label:'EC2 Instance',color:'#ed7100',category:'Compute',defaults:{instanceType:'t3.micro',ami:'ami-0c02fb55956c7d316'}},
  lambda:{label:'Lambda',color:'#ed7100',category:'Compute',defaults:{runtime:'nodejs20.x',handler:'index.handler'}},
  s3:{label:'S3 Bucket',color:'#3f8624',category:'Storage',defaults:{versioning:'true'}},
  dynamodb:{label:'DynamoDB',color:'#3b48cc',category:'Database',defaults:{partitionKey:'id'}},
  rds:{label:'RDS PostgreSQL',color:'#3b48cc',category:'Database',defaults:{instanceClass:'db.t3.micro',engineVersion:'16.3'}},
  apigw:{label:'API Gateway',color:'#a166ff',category:'Integration',defaults:{}},
  iam_role:{label:'IAM Role',color:'#dd344c',category:'Security',defaults:{service:'lambda.amazonaws.com'}},
  cloudwatch:{label:'CloudWatch Log Group',color:'#e7157b',category:'Management',defaults:{retentionDays:'14'}},
  kinesis:{label:'Kinesis Data Streams',color:'#8c4fff',category:'Analytics',defaults:{shards:'1'}},
  glue:{label:'AWS Glue Data Catalog',color:'#8c4fff',category:'Analytics',defaults:{database:'analytics'}},
  lakeformation:{label:'AWS Lake Formation',color:'#8c4fff',category:'Analytics',defaults:{}},
  emr_serverless:{label:'EMR Serverless',color:'#8c4fff',category:'Analytics',defaults:{releaseLabel:'emr-7.5.0'}},
  athena:{label:'Amazon Athena',color:'#8c4fff',category:'Analytics',defaults:{workgroup:'primary'}},
  redshift_serverless:{label:'Redshift Serverless',color:'#8c4fff',category:'Analytics',defaults:{baseCapacity:'8'}},
  quicksight:{label:'Amazon QuickSight',color:'#8c4fff',category:'Analytics',defaults:{}},
  sagemaker:{label:'Amazon SageMaker',color:'#01a88d',category:'Machine Learning',defaults:{}},
  cognito:{label:'Amazon Cognito',color:'#dd344c',category:'Security',defaults:{}},
  bedrock:{label:'Amazon Bedrock',color:'#01a88d',category:'Generative AI',defaults:{model:'anthropic.claude-3-5-sonnet'}},
  bedrock_kb:{label:'Bedrock Knowledge Base',color:'#01a88d',category:'Generative AI',defaults:{}},
  bedrock_agent:{label:'Bedrock Agent',color:'#01a88d',category:'Generative AI',defaults:{role:'specialist'}},
  opensearch:{label:'OpenSearch Serverless',color:'#3b48cc',category:'Database',defaults:{}},
  step_functions:{label:'AWS Step Functions',color:'#e7157b',category:'Integration',defaults:{}},
  eventbridge:{label:'Amazon EventBridge',color:'#e7157b',category:'Integration',defaults:{}}
};

const id=s=>s.replace(/[^a-zA-Z0-9_]/g,'_').toLowerCase();
const q=s=>JSON.stringify(String(s));
export function validateGraph(graph){const issues=[];const byId=Object.fromEntries(graph.nodes.map(n=>[n.id,n]));const incoming=x=>graph.edges.filter(e=>e.target===x).map(e=>byId[e.source]);for(const n of graph.nodes){if(!n.name?.trim())issues.push({level:'error',message:`${n.type} has no name`});if(n.type==='subnet'&&!incoming(n.id).some(x=>x?.type==='vpc'))issues.push({level:'error',message:`${n.name} must connect from a VPC`});if(n.type==='ec2'&&!incoming(n.id).some(x=>x?.type==='subnet'))issues.push({level:'error',message:`${n.name} must connect from a subnet`});if(n.type==='rds'&&!incoming(n.id).some(x=>x?.type==='subnet'))issues.push({level:'error',message:`${n.name} needs at least one subnet connection`});if(n.type==='apigw'&&!graph.edges.some(e=>e.source===n.id&&byId[e.target]?.type==='lambda'))issues.push({level:'warning',message:`${n.name} has no Lambda integration`});if(n.type==='s3'&&!/^[a-z0-9.-]+$/.test(n.name))issues.push({level:'error',message:`S3 bucket name “${n.name}” is invalid`});}if(!graph.nodes.length)issues.push({level:'warning',message:'Architecture is empty'});return issues}

export function terraform(graph){const byId=Object.fromEntries(graph.nodes.map(n=>[n.id,n]));const incoming=x=>graph.edges.filter(e=>e.target===x).map(e=>byId[e.source]);let out=`terraform {\n  required_providers { aws = { source = "hashicorp/aws" version = "~> 5.0" } }\n}\n\nprovider "aws" { region = var.aws_region }\nvariable "aws_region" { type = string default = "eu-north-1" }\n`;
for(const n of graph.nodes){const r=id(n.name),p=n.props||{};if(n.type==='vpc')out+=`\nresource "aws_vpc" "${r}" { cidr_block = ${q(p.cidr)} enable_dns_hostnames = true tags = { Name = ${q(n.name)} } }\n`;if(n.type==='subnet'){const v=incoming(n.id).find(x=>x?.type==='vpc');out+=`\nresource "aws_subnet" "${r}" { vpc_id = ${v?`aws_vpc.${id(v.name)}.id`:'null'} cidr_block = ${q(p.cidr)} map_public_ip_on_launch = ${p.public==='true'} tags = { Name = ${q(n.name)} } }\n`;}if(n.type==='security_group'){const v=incoming(n.id).find(x=>x?.type==='vpc');out+=`\nresource "aws_security_group" "${r}" { name = ${q(n.name)} description = ${q(p.description)} vpc_id = ${v?`aws_vpc.${id(v.name)}.id`:'null'} }\n`;}if(n.type==='ec2'){const s=incoming(n.id).find(x=>x?.type==='subnet');out+=`\nresource "aws_instance" "${r}" { ami = ${q(p.ami)} instance_type = ${q(p.instanceType)} subnet_id = ${s?`aws_subnet.${id(s.name)}.id`:'null'} tags = { Name = ${q(n.name)} } }\n`;}if(n.type==='s3')out+=`\nresource "aws_s3_bucket" "${r}" { bucket = ${q(n.name)} }\nresource "aws_s3_bucket_versioning" "${r}" { bucket = aws_s3_bucket.${r}.id versioning_configuration { status = "${p.versioning==='true'?'Enabled':'Suspended'}" } }\n`;if(n.type==='lambda')out+=`\nresource "aws_lambda_function" "${r}" { function_name = ${q(n.name)} role = aws_iam_role.${r}.arn runtime = ${q(p.runtime)} handler = ${q(p.handler)} filename = "lambda.zip" }\nresource "aws_iam_role" "${r}" { name = "${r}-execution" assume_role_policy = jsonencode({ Version="2012-10-17", Statement=[{Action="sts:AssumeRole",Effect="Allow",Principal={Service="lambda.amazonaws.com"}}] }) }\n`;if(n.type==='dynamodb')out+=`\nresource "aws_dynamodb_table" "${r}" { name=${q(n.name)} billing_mode="PAY_PER_REQUEST" hash_key=${q(p.partitionKey)} attribute { name=${q(p.partitionKey)} type="S" } }\n`;if(n.type==='cloudwatch')out+=`\nresource "aws_cloudwatch_log_group" "${r}" { name=${q(n.name)} retention_in_days=${Number(p.retentionDays)||14} }\n`;if(n.type==='rds')out+=`\nresource "aws_db_instance" "${r}" { identifier=${q(n.name)} engine="postgres" engine_version=${q(p.engineVersion)} instance_class=${q(p.instanceClass)} allocated_storage=20 username="appuser" manage_master_user_password=true skip_final_snapshot=true }\n`;if(n.type==='apigw')out+=`\nresource "aws_apigatewayv2_api" "${r}" { name=${q(n.name)} protocol_type="HTTP" }\n`;if(n.type==='iam_role')out+=`\nresource "aws_iam_role" "${r}" { name=${q(n.name)} assume_role_policy=jsonencode({Version="2012-10-17",Statement=[{Action="sts:AssumeRole",Effect="Allow",Principal={Service=${q(p.service)}}}]}) }\n`;}
return out}

export function cdk(graph){const vars=graph.nodes.map(n=>`    const ${id(n.name)} = ${cdkNode(n,graph)};`).join('\n');return `import * as cdk from 'aws-cdk-lib';\nimport * as ec2 from 'aws-cdk-lib/aws-ec2';\nimport * as s3 from 'aws-cdk-lib/aws-s3';\nimport * as lambda from 'aws-cdk-lib/aws-lambda';\nimport * as dynamodb from 'aws-cdk-lib/aws-dynamodb';\nimport * as logs from 'aws-cdk-lib/aws-logs';\nimport { Construct } from 'constructs';\n\nexport class CloudSketchStack extends cdk.Stack {\n  constructor(scope: Construct, id: string, props?: cdk.StackProps) {\n    super(scope, id, props);\n${vars}\n  }\n}\n`}
function cdkNode(n,g){const p=n.props||{},r=id(n.name);switch(n.type){case'vpc':return`new ec2.Vpc(this, '${r}', { ipAddresses: ec2.IpAddresses.cidr(${q(p.cidr)}), natGateways: 0 })`;case's3':return`new s3.Bucket(this, '${r}', { bucketName: ${q(n.name)}, versioned: ${p.versioning==='true'}, removalPolicy: cdk.RemovalPolicy.RETAIN })`;case'lambda':return`new lambda.Function(this, '${r}', { runtime: lambda.Runtime.NODEJS_20_X, handler: ${q(p.handler)}, code: lambda.Code.fromAsset('lambda') })`;case'dynamodb':return`new dynamodb.Table(this, '${r}', { partitionKey: { name: ${q(p.partitionKey)}, type: dynamodb.AttributeType.STRING }, billingMode: dynamodb.BillingMode.PAY_PER_REQUEST })`;case'cloudwatch':return`new logs.LogGroup(this, '${r}', { retention: logs.RetentionDays.TWO_WEEKS })`;default:return`/* ${n.type}: configure with an L2 construct */ { nodeType: ${q(n.type)}, name: ${q(n.name)} }`;}}
